version: "3.9"

services:
   db:
      image: "postgres"
      ports:
         - "4444:5432"
      environment:
         POSTGRES_USER: "postgres"
         POSTGRES_PASSWORD: "root"
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U postgres"]
         interval: 10s
         timeout: 5s
         retries: 5

   server:
      build: .
      ports:
         - "8080:8080"
      depends_on:
         db:
            condition: service_healthy
